# Generated by Django 3.0.10 on 2021-04-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0015_auto_20210421_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='keysequence',
            name='verify_method',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
