# Generated by Django 3.0.10 on 2021-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0016_keysequence_verify_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyauditreport',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='keyauditreport',
            name='confirmed_at',
        ),
        migrations.AddField(
            model_name='keygroup',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='keygroup',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keysequence',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='keysequence',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
