# Generated by Django 3.0.10 on 2021-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0017_auto_20210427_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keygroup',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='keysequence',
            name='confirm',
        ),
        migrations.AddField(
            model_name='keygroup',
            name='audit_status',
            field=models.CharField(choices=[('pending', 'Available for Confirmation'), ('rejected', 'Rejected by someone'), ('confirmed', 'Confirmed by someone')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='keysequence',
            name='audit_status',
            field=models.CharField(choices=[('pending', 'Available for Confirmation'), ('rejected', 'Rejected by someone'), ('confirmed', 'Confirmed by someone')], default='pending', max_length=32),
        ),
    ]
