# Generated by Django 3.0.10 on 2021-04-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0018_auto_20210427_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keygroup',
            name='audit_status',
            field=models.CharField(choices=[('pending', 'Available for Confirmation'), ('waiting_for_confirmation', 'Waiting for Confirmation'), ('rejected', 'Rejected by someone'), ('confirmed', 'Confirmed by someone')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='keysequence',
            name='audit_status',
            field=models.CharField(choices=[('pending', 'Available for Confirmation'), ('waiting_for_confirmation', 'Waiting for Confirmation'), ('rejected', 'Rejected by someone'), ('confirmed', 'Confirmed by someone')], default='pending', max_length=32),
        ),
    ]
