# Generated by Django 3.0.10 on 2021-04-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0016_filenumber_system_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenumber',
            name='file_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
