# Generated by Django 3.0.10 on 2021-08-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0017_auto_20210427_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
